server:
  port: 8881
spring:
  application:
    name: register-center
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info #eureka注册中心的url link
    health-check-url-path: /actuator/health #健康检查的url
    hostname: localhost
    instance-id: ${spring.application.name}:${eureka.instance.ipAddress}:${server.port}
  client:
    register-with-eureka: true #是否注册到注册中心
    fetch-registry: false #是否从注册中心拉取注册服务列表
    service-url:
      defaultZone: http://localhost:8881/eureka/


