server:
  port: 8803
spring:
  cloud:
    zookeeper:
      discovery:
        instance-host: localhost
        instance-port: 8080
        register: false
      connect-string: localhost:2181
  application:
    name: customer-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.125:3306/test
    username: root
    password: 1qaz!QAZ
  redis:
     password: test2018
     sentinel:
       master: cement_master
       nodes: 192.168.1.125:26379,192.168.1.125:26380,192.168.1.125:26381
mybatis:
  mapper-locations: classpath:mapping/*.xml
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /security/status #eureka注册中心的url link
    health-check-url-path: /actuator/health #健康检查的url
    hostname: 127.0.0.1
    instance-id: CUSTOMER-SERVICE
  client:
    register-with-eureka: true #是否注册到注册中心
    fetch-registry: true #是否从注册中心拉取注册服务列表
    service-url:
      defaultZone: http://localhost:8881/eureka/

#feign配置，可以针对单个feignClient单独配置
feign:
  client:
    config:
      auth-center:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: basic

logging:
  config: classpath:logback-config.xml


